version: '2.4'

services:

  pythonutil_3_9_16:
    build: 
      context: ./version_3_9_16
      dockerfile: Dockerfile
    container_name: pythonutil_3_9_16
    restart: unless-stopped
    env_file:
      - env_file
    volumes:
      - ../../:/home/python/projects
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /home/python
    command: ./entrypoint.sh

  pythonutil_3_10:
    build: 
      context: ./version_3_10
      dockerfile: Dockerfile
    container_name: pythonutil_3_10
    restart: unless-stopped
    env_file:
      - env_file
    volumes:
      - ../../:/home/python/projects
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /home/python
    command: ./entrypoint.sh