version: '2.4'

services:

  pythonutil_3_9_16:
    build: 
      dockerfile: Dockerfile_3_9_16
      context: ./
    container_name: pythonutil_3_9_16
    env_file:
      - env_file
    volumes:
      - ../../:/home/python/projects
    working_dir: /home/python
    entrypoint: tail
    command: -f /dev/null

  pythonutil_3_10:
    build: 
      dockerfile: Dockerfile_3_10
      context: ./
    container_name: pythonutil_3_10
    env_file:
      - env_file
    volumes:
      - ../../:/home/python/projects
    working_dir: /home/python
    entrypoint: tail
    command: -f /dev/null